services:
  backend:
    image: code-judge-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://yousef:code-judge123@db:5432/code_judge?sslmode=disable
      - JWT_SECRET=your-secret-key-for-jwt
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend/config:/app/config
  
  frontend:
    image: code-judge-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "2020:2020"
    environment:
      - API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend/templates:/app/templates
      - ./frontend/static:/app/static
  
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: yousef
      POSTGRES_PASSWORD: code-judge123
      POSTGRES_DB: code_judge
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge